# Generated by Django 5.1.1 on 2025-02-16 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                ("bill_id", models.AutoField(primary_key=True, serialize=False)),
                ("bill_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bill_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "arrears",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "concession",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "consumer_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
