# Generated by Django 5.1.1 on 2025-02-16 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_name", models.CharField(max_length=100)),
                ("installment_frequency_days", models.IntegerField()),
                ("installment_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("payment_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Completed", "Completed"), ("Failed", "Failed")],
                        max_length=10,
                    ),
                ),
                (
                    "bill_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.billing",
                    ),
                ),
                (
                    "payment_method_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.paymentmethod",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YearlyPayments",
            fields=[
                ("yearly_id", models.AutoField(primary_key=True, serialize=False)),
                ("yearly_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("last_deduction_date", models.DateField()),
                ("refill_status", models.BooleanField(default=False)),
                (
                    "consumer_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
