# Generated by Django 5.1.1 on 2025-04-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_userinstallments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="payment_method_id",
        ),
        migrations.RemoveField(
            model_name="userinstallments",
            name="plan",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
