# Generated by Django 5.1.1 on 2024-12-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="Category",
        ),
        migrations.AlterModelTable(
            name="complaint",
            table="Complaint",
        ),
        migrations.AlterModelTable(
            name="furthersubcategory",
            table="FurtherSubCategory",
        ),
        migrations.AlterModelTable(
            name="subcategory",
            table="SubCategory",
        ),
    ]
