# Generated by Django 5.1.1 on 2025-02-16 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("consumer_no", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=11, unique=True)),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("cnic", models.CharField(max_length=13)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_type",
                    models.IntegerField(
                        choices=[(1, "Installments"), (2, "Monthly"), (3, "Yearly")],
                        default=1,
                    ),
                ),
                ("xps", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "reset_token",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("jwt_token", models.CharField(blank=True, max_length=500, null=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "Users",
            },
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("secret", models.CharField(max_length=100)),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
