# Generated by Django 5.1.1 on 2025-04-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="billing_type",
            field=models.IntegerField(
                choices=[
                    (1, "Installments"),
                    (2, "Monthly"),
                    (3, "Yearly-15"),
                    (4, "Yearly-10"),
                ],
                default=1,
            ),
        ),
    ]
