# Generated by Django 5.1.1 on 2025-04-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_billing_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="billing_type",
            field=models.IntegerField(
                choices=[
                    (1, "Installments-10"),
                    (2, "Installments-15"),
                    (3, "Monthly"),
                    (4, "Yearly"),
                ],
                default=1,
            ),
        ),
    ]
